[target.x86_64-unknown-linux-musl]
linker = "rust-lld"
rustflags = ["-Ctarget-feature=+crt-static"]


[target.x86_64-unknown-linux-musl.pq]
rustc-link-search = ["C:\\Program Files\\PostgreSQL\\14\\lib"]
rustc-link-lib = ["libpq"]


